/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { CombinedSubmissionAction } from "./combinedSubmissionAction";

export class CombinedSubmission {
  "id": string;
  "expired": boolean;
  "expiresIn"?: number | null;
  "expiresAt"?: string | null;
  "state": CombinedSubmission.StateEnum;
  "errorMessage"?: string | null;
  "metadata"?: object;
  "password"?: string | null;
  "submissionIds": Array<string>;
  "sourcePdfs": Array<object>;
  "downloadUrl"?: string | null;
  "pdfHash"?: string | null;
  "actions"?: Array<CombinedSubmissionAction>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "expired",
      baseName: "expired",
      type: "boolean",
    },
    {
      name: "expiresIn",
      baseName: "expires_in",
      type: "number",
    },
    {
      name: "expiresAt",
      baseName: "expires_at",
      type: "string",
    },
    {
      name: "state",
      baseName: "state",
      type: "CombinedSubmission.StateEnum",
    },
    {
      name: "errorMessage",
      baseName: "error_message",
      type: "string",
    },
    {
      name: "metadata",
      baseName: "metadata",
      type: "object",
    },
    {
      name: "password",
      baseName: "password",
      type: "string",
    },
    {
      name: "submissionIds",
      baseName: "submission_ids",
      type: "Array<string>",
    },
    {
      name: "sourcePdfs",
      baseName: "source_pdfs",
      type: "Array<object>",
    },
    {
      name: "downloadUrl",
      baseName: "download_url",
      type: "string",
    },
    {
      name: "pdfHash",
      baseName: "pdf_hash",
      type: "string",
    },
    {
      name: "actions",
      baseName: "actions",
      type: "Array<CombinedSubmissionAction>",
    },
  ];

  static getAttributeTypeMap() {
    return CombinedSubmission.attributeTypeMap;
  }
}

export namespace CombinedSubmission {
  export enum StateEnum {
    Pending = "pending",
    Processed = "processed",
    Error = "error",
  }
}
