/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class CombinedSubmissionAction {
  "id": string;
  "integrationId": string | null;
  "state": CombinedSubmissionAction.StateEnum;
  "actionCategory": CombinedSubmissionAction.ActionCategoryEnum;
  "actionType": CombinedSubmissionAction.ActionTypeEnum;
  "resultData": object;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "integrationId",
      baseName: "integration_id",
      type: "string",
    },
    {
      name: "state",
      baseName: "state",
      type: "CombinedSubmissionAction.StateEnum",
    },
    {
      name: "actionCategory",
      baseName: "action_category",
      type: "CombinedSubmissionAction.ActionCategoryEnum",
    },
    {
      name: "actionType",
      baseName: "action_type",
      type: "CombinedSubmissionAction.ActionTypeEnum",
    },
    {
      name: "resultData",
      baseName: "result_data",
      type: "object",
    },
  ];

  static getAttributeTypeMap() {
    return CombinedSubmissionAction.attributeTypeMap;
  }
}

export namespace CombinedSubmissionAction {
  export enum StateEnum {
    Pending = "pending",
    Processed = "processed",
    Failed = "failed",
    Error = "error",
  }
  export enum ActionCategoryEnum {
    Notification = "notification",
    FileUpload = "file_upload",
  }
  export enum ActionTypeEnum {
    Webhook = "webhook",
    SlackWebhook = "slack_webhook",
    Email = "email",
    AwsS3Upload = "aws_s3_upload",
  }
}
