/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { CombinedSubmission } from "./combinedSubmission";

export class CreateCombinedSubmissionResponse {
  "status": CreateCombinedSubmissionResponse.StatusEnum;
  "errors"?: Array<string>;
  "combinedSubmission": CombinedSubmission;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "status",
      baseName: "status",
      type: "CreateCombinedSubmissionResponse.StatusEnum",
    },
    {
      name: "errors",
      baseName: "errors",
      type: "Array<string>",
    },
    {
      name: "combinedSubmission",
      baseName: "combined_submission",
      type: "CombinedSubmission",
    },
  ];

  static getAttributeTypeMap() {
    return CreateCombinedSubmissionResponse.attributeTypeMap;
  }
}

export namespace CreateCombinedSubmissionResponse {
  export enum StatusEnum {
    Success = "success",
    Error = "error",
  }
}
