/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { Submission } from "./submission";

export class CreateSubmissionResponse {
  "status": CreateSubmissionResponse.StatusEnum;
  "errors"?: Array<string>;
  "submission": Submission;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "status",
      baseName: "status",
      type: "CreateSubmissionResponse.StatusEnum",
    },
    {
      name: "errors",
      baseName: "errors",
      type: "Array<string>",
    },
    {
      name: "submission",
      baseName: "submission",
      type: "Submission",
    },
  ];

  static getAttributeTypeMap() {
    return CreateSubmissionResponse.attributeTypeMap;
  }
}

export namespace CreateSubmissionResponse {
  export enum StatusEnum {
    Success = "success",
    Error = "error",
  }
}
