/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateSubmissionDataRequestTokenResponseToken {
    'id': string;
    'secret': string;
    'expiresAt': string;
    'dataRequestUrl': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string"
        },
        {
            "name": "dataRequestUrl",
            "baseName": "data_request_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubmissionDataRequestTokenResponseToken.attributeTypeMap;
    }
}

