/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { CreateSubmissionBatchSubmissionsResponse } from "./createSubmissionBatchSubmissionsResponse";
import { SubmissionBatch } from "./submissionBatch";

export class CreateSubmissionBatchResponse {
  "status": CreateSubmissionBatchResponse.StatusEnum;
  "error"?: string;
  "errors"?: Array<string>;
  "submissionBatch": SubmissionBatch;
  "submissions": Array<CreateSubmissionBatchSubmissionsResponse>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "status",
      baseName: "status",
      type: "CreateSubmissionBatchResponse.StatusEnum",
    },
    {
      name: "error",
      baseName: "error",
      type: "string",
    },
    {
      name: "errors",
      baseName: "errors",
      type: "Array<string>",
    },
    {
      name: "submissionBatch",
      baseName: "submission_batch",
      type: "SubmissionBatch",
    },
    {
      name: "submissions",
      baseName: "submissions",
      type: "Array<CreateSubmissionBatchSubmissionsResponse>",
    },
  ];

  static getAttributeTypeMap() {
    return CreateSubmissionBatchResponse.attributeTypeMap;
  }
}

export namespace CreateSubmissionBatchResponse {
  export enum StatusEnum {
    Success = "success",
    Error = "error",
  }
}
