/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { FullTemplateDefaults } from "./fullTemplateDefaults";

export class FullTemplate {
  "name": string | null;
  "description": string | null;
  "publicWebForm": boolean;
  "publicSubmissions": boolean;
  "expireSubmissions": boolean;
  "expireAfter": number;
  "expirationInterval": FullTemplate.ExpirationIntervalEnum;
  "allowAdditionalProperties": boolean;
  "editableSubmissions": boolean;
  "locked": boolean;
  "webhookUrl": string | null;
  "slackWebhookUrl": string | null;
  "redirectUrl": string | null;
  "firstTemplate": boolean;
  "html": string | null;
  "headerHtml": string | null;
  "footerHtml": string | null;
  "scss": string | null;
  "encryptPdfs": boolean;
  "encryptPdfsPassword": string | null;
  "defaults": FullTemplateDefaults;
  "fields": object;
  "sharedFieldData": object;
  "fieldOrder": Array<Array<number>>;
  "documentMd5": string | null;
  "documentFilename": string | null;
  "documentParseError": boolean;
  "documentState": string;
  "embedDomains": Array<string> | null;
  "pageCount": number;
  "documentProcessed": boolean;
  "demo": boolean;
  "id": string;
  "templateType": string;
  "pageDimensions": Array<Array<number>> | null;
  "documentUrl": string | null;
  "permanentDocumentUrl": string | null;
  "path": string;
  "parentFolderId": string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
    },
    {
      name: "publicWebForm",
      baseName: "public_web_form",
      type: "boolean",
    },
    {
      name: "publicSubmissions",
      baseName: "public_submissions",
      type: "boolean",
    },
    {
      name: "expireSubmissions",
      baseName: "expire_submissions",
      type: "boolean",
    },
    {
      name: "expireAfter",
      baseName: "expire_after",
      type: "number",
    },
    {
      name: "expirationInterval",
      baseName: "expiration_interval",
      type: "FullTemplate.ExpirationIntervalEnum",
    },
    {
      name: "allowAdditionalProperties",
      baseName: "allow_additional_properties",
      type: "boolean",
    },
    {
      name: "editableSubmissions",
      baseName: "editable_submissions",
      type: "boolean",
    },
    {
      name: "locked",
      baseName: "locked",
      type: "boolean",
    },
    {
      name: "webhookUrl",
      baseName: "webhook_url",
      type: "string",
    },
    {
      name: "slackWebhookUrl",
      baseName: "slack_webhook_url",
      type: "string",
    },
    {
      name: "redirectUrl",
      baseName: "redirect_url",
      type: "string",
    },
    {
      name: "firstTemplate",
      baseName: "first_template",
      type: "boolean",
    },
    {
      name: "html",
      baseName: "html",
      type: "string",
    },
    {
      name: "headerHtml",
      baseName: "header_html",
      type: "string",
    },
    {
      name: "footerHtml",
      baseName: "footer_html",
      type: "string",
    },
    {
      name: "scss",
      baseName: "scss",
      type: "string",
    },
    {
      name: "encryptPdfs",
      baseName: "encrypt_pdfs",
      type: "boolean",
    },
    {
      name: "encryptPdfsPassword",
      baseName: "encrypt_pdfs_password",
      type: "string",
    },
    {
      name: "defaults",
      baseName: "defaults",
      type: "FullTemplateDefaults",
    },
    {
      name: "fields",
      baseName: "fields",
      type: "object",
    },
    {
      name: "sharedFieldData",
      baseName: "shared_field_data",
      type: "object",
    },
    {
      name: "fieldOrder",
      baseName: "field_order",
      type: "Array<Array<number>>",
    },
    {
      name: "documentMd5",
      baseName: "document_md5",
      type: "string",
    },
    {
      name: "documentFilename",
      baseName: "document_filename",
      type: "string",
    },
    {
      name: "documentParseError",
      baseName: "document_parse_error",
      type: "boolean",
    },
    {
      name: "documentState",
      baseName: "document_state",
      type: "string",
    },
    {
      name: "embedDomains",
      baseName: "embed_domains",
      type: "Array<string>",
    },
    {
      name: "pageCount",
      baseName: "page_count",
      type: "number",
    },
    {
      name: "documentProcessed",
      baseName: "document_processed",
      type: "boolean",
    },
    {
      name: "demo",
      baseName: "demo",
      type: "boolean",
    },
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "templateType",
      baseName: "template_type",
      type: "string",
    },
    {
      name: "pageDimensions",
      baseName: "page_dimensions",
      type: "Array<Array<number>>",
    },
    {
      name: "documentUrl",
      baseName: "document_url",
      type: "string",
    },
    {
      name: "permanentDocumentUrl",
      baseName: "permanent_document_url",
      type: "string",
    },
    {
      name: "path",
      baseName: "path",
      type: "string",
    },
    {
      name: "parentFolderId",
      baseName: "parent_folder_id",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return FullTemplate.attributeTypeMap;
  }
}

export namespace FullTemplate {
  export enum ExpirationIntervalEnum {
    Minutes = "minutes",
    Hours = "hours",
    Days = "days",
  }
}
