/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class HtmlTemplateData {
  "allowAdditionalProperties"?: boolean;
  "description"?: string | null;
  "editableSubmissions"?: boolean;
  "expirationInterval"?: HtmlTemplateData.ExpirationIntervalEnum;
  "expireAfter"?: number;
  "expireSubmissions"?: boolean;
  "footerHtml"?: string | null;
  "headerHtml"?: string | null;
  "html"?: string | null;
  "name": string | null;
  "publicSubmissions"?: boolean;
  "publicWebForm"?: boolean;
  "redirectUrl"?: string | null;
  "scss"?: string | null;
  "slackWebhookUrl"?: string | null;
  "templateType"?: HtmlTemplateData.TemplateTypeEnum;
  "webhookUrl"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "allowAdditionalProperties",
      baseName: "allow_additional_properties",
      type: "boolean",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
    },
    {
      name: "editableSubmissions",
      baseName: "editable_submissions",
      type: "boolean",
    },
    {
      name: "expirationInterval",
      baseName: "expiration_interval",
      type: "HtmlTemplateData.ExpirationIntervalEnum",
    },
    {
      name: "expireAfter",
      baseName: "expire_after",
      type: "number",
    },
    {
      name: "expireSubmissions",
      baseName: "expire_submissions",
      type: "boolean",
    },
    {
      name: "footerHtml",
      baseName: "footer_html",
      type: "string",
    },
    {
      name: "headerHtml",
      baseName: "header_html",
      type: "string",
    },
    {
      name: "html",
      baseName: "html",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "publicSubmissions",
      baseName: "public_submissions",
      type: "boolean",
    },
    {
      name: "publicWebForm",
      baseName: "public_web_form",
      type: "boolean",
    },
    {
      name: "redirectUrl",
      baseName: "redirect_url",
      type: "string",
    },
    {
      name: "scss",
      baseName: "scss",
      type: "string",
    },
    {
      name: "slackWebhookUrl",
      baseName: "slack_webhook_url",
      type: "string",
    },
    {
      name: "templateType",
      baseName: "template_type",
      type: "HtmlTemplateData.TemplateTypeEnum",
    },
    {
      name: "webhookUrl",
      baseName: "webhook_url",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return HtmlTemplateData.attributeTypeMap;
  }
}

export namespace HtmlTemplateData {
  export enum ExpirationIntervalEnum {
    Minutes = "minutes",
    Hours = "hours",
    Days = "days",
  }
  export enum TemplateTypeEnum {
    Pdf = "pdf",
    Html = "html",
  }
}
