/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Submission } from './submission';

export class ListSubmissionsResponse {
    'submissions': Array<Submission>;
    'limit': number;
    'nextCursor': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "submissions",
            "baseName": "submissions",
            "type": "Array<Submission>"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "nextCursor",
            "baseName": "next_cursor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListSubmissionsResponse.attributeTypeMap;
    }
}

