/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class PendingTemplate {
  "id": string;
  "name": string | null;
  "description": string | null;
  "templateType": string;
  "publicWebForm": boolean;
  "publicSubmissions": boolean;
  "expireSubmissions": boolean;
  "expireAfter"?: number;
  "locked": boolean;
  "expirationInterval"?: PendingTemplate.ExpirationIntervalEnum;
  "allowAdditionalProperties": boolean;
  "editableSubmissions": boolean;
  "webhookUrl": string | null;
  "slackWebhookUrl": string | null;
  "redirectUrl": string | null;
  "path"?: string;
  "parentFolderId"?: string | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
    },
    {
      name: "templateType",
      baseName: "template_type",
      type: "string",
    },
    {
      name: "publicWebForm",
      baseName: "public_web_form",
      type: "boolean",
    },
    {
      name: "publicSubmissions",
      baseName: "public_submissions",
      type: "boolean",
    },
    {
      name: "expireSubmissions",
      baseName: "expire_submissions",
      type: "boolean",
    },
    {
      name: "expireAfter",
      baseName: "expire_after",
      type: "number",
    },
    {
      name: "locked",
      baseName: "locked",
      type: "boolean",
    },
    {
      name: "expirationInterval",
      baseName: "expiration_interval",
      type: "PendingTemplate.ExpirationIntervalEnum",
    },
    {
      name: "allowAdditionalProperties",
      baseName: "allow_additional_properties",
      type: "boolean",
    },
    {
      name: "editableSubmissions",
      baseName: "editable_submissions",
      type: "boolean",
    },
    {
      name: "webhookUrl",
      baseName: "webhook_url",
      type: "string",
    },
    {
      name: "slackWebhookUrl",
      baseName: "slack_webhook_url",
      type: "string",
    },
    {
      name: "redirectUrl",
      baseName: "redirect_url",
      type: "string",
    },
    {
      name: "path",
      baseName: "path",
      type: "string",
    },
    {
      name: "parentFolderId",
      baseName: "parent_folder_id",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return PendingTemplate.attributeTypeMap;
  }
}

export namespace PendingTemplate {
  export enum ExpirationIntervalEnum {
    Minutes = "minutes",
    Hours = "hours",
    Days = "days",
  }
}
