/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { Submission } from "./submission";

export class SubmissionBatch {
  "id": string;
  "totalCount": number;
  "pendingCount": number;
  "errorCount": number;
  "completionPercentage": number;
  "state": SubmissionBatch.StateEnum;
  "processedAt": string | null;
  "metadata": object;
  "submissions"?: Array<Submission>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "totalCount",
      baseName: "total_count",
      type: "number",
    },
    {
      name: "pendingCount",
      baseName: "pending_count",
      type: "number",
    },
    {
      name: "errorCount",
      baseName: "error_count",
      type: "number",
    },
    {
      name: "completionPercentage",
      baseName: "completion_percentage",
      type: "number",
    },
    {
      name: "state",
      baseName: "state",
      type: "SubmissionBatch.StateEnum",
    },
    {
      name: "processedAt",
      baseName: "processed_at",
      type: "string",
    },
    {
      name: "metadata",
      baseName: "metadata",
      type: "object",
    },
    {
      name: "submissions",
      baseName: "submissions",
      type: "Array<Submission>",
    },
  ];

  static getAttributeTypeMap() {
    return SubmissionBatch.attributeTypeMap;
  }
}

export namespace SubmissionBatch {
  export enum StateEnum {
    Pending = "pending",
    Processed = "processed",
    Error = "error",
  }
}
