/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TemplateSchema {
    '$schema'?: string;
    'id'?: string;
    'title'?: string;
    'description'?: string;
    'definitions'?: object;
    'type'?: string;
    'properties'?: object;
    'additionalProperties'?: boolean;
    'required'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "definitions",
            "baseName": "definitions",
            "type": "object"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        },
        {
            "name": "additionalProperties",
            "baseName": "additionalProperties",
            "type": "boolean"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return TemplateSchema.attributeTypeMap;
    }
}

