/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { SubmissionDataRequest } from "./submissionDataRequest";

export class UpdateDataRequestResponse {
  "status": UpdateDataRequestResponse.StatusEnum;
  "errors"?: Array<string>;
  "dataRequest": SubmissionDataRequest;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "status",
      baseName: "status",
      type: "UpdateDataRequestResponse.StatusEnum",
    },
    {
      name: "errors",
      baseName: "errors",
      type: "Array<string>",
    },
    {
      name: "dataRequest",
      baseName: "data_request",
      type: "SubmissionDataRequest",
    },
  ];

  static getAttributeTypeMap() {
    return UpdateDataRequestResponse.attributeTypeMap;
  }
}

export namespace UpdateDataRequestResponse {
  export enum StatusEnum {
    Success = "success",
    Error = "error",
  }
}
