/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class UploadTemplateDataDocumentMetadata {
  "filename": string;
  "mimeType": UploadTemplateDataDocumentMetadata.MimeTypeEnum;
  "size": number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "filename",
      baseName: "filename",
      type: "string",
    },
    {
      name: "mimeType",
      baseName: "mime_type",
      type: "UploadTemplateDataDocumentMetadata.MimeTypeEnum",
    },
    {
      name: "size",
      baseName: "size",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return UploadTemplateDataDocumentMetadata.attributeTypeMap;
  }
}

export namespace UploadTemplateDataDocumentMetadata {
  export enum MimeTypeEnum {
    ApplicationPdf = "application/pdf",
  }
}
