/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UploadPresignFields {
    'key': string;
    'policy': string;
    'xAmzAlgorithm': string;
    'xAmzCredential': string;
    'xAmzDate': string;
    'xAmzSignature': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "string"
        },
        {
            "name": "xAmzAlgorithm",
            "baseName": "x-amz-algorithm",
            "type": "string"
        },
        {
            "name": "xAmzCredential",
            "baseName": "x-amz-credential",
            "type": "string"
        },
        {
            "name": "xAmzDate",
            "baseName": "x-amz-date",
            "type": "string"
        },
        {
            "name": "xAmzSignature",
            "baseName": "x-amz-signature",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UploadPresignFields.attributeTypeMap;
    }
}

