/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { UploadPresignFields } from "./uploadPresignFields";

export class UploadPresign {
  "fields": UploadPresignFields;
  "headers": object;
  "url": string;
  "method"?: UploadPresign.MethodEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "fields",
      baseName: "fields",
      type: "UploadPresignFields",
    },
    {
      name: "headers",
      baseName: "headers",
      type: "object",
    },
    {
      name: "url",
      baseName: "url",
      type: "string",
    },
    {
      name: "method",
      baseName: "method",
      type: "UploadPresign.MethodEnum",
    },
  ];

  static getAttributeTypeMap() {
    return UploadPresign.attributeTypeMap;
  }
}

export namespace UploadPresign {
  export enum MethodEnum {
    Post = "post",
  }
}
