/**
 * API v1
 * DocSpring is a service that helps you fill out and sign PDF templates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { UploadTemplateDataDocumentMetadata } from "./uploadTemplateDataDocumentMetadata";

export class UploadTemplateDataDocument {
  "id": string;
  "metadata": UploadTemplateDataDocumentMetadata;
  "storage": UploadTemplateDataDocument.StorageEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "metadata",
      baseName: "metadata",
      type: "UploadTemplateDataDocumentMetadata",
    },
    {
      name: "storage",
      baseName: "storage",
      type: "UploadTemplateDataDocument.StorageEnum",
    },
  ];

  static getAttributeTypeMap() {
    return UploadTemplateDataDocument.attributeTypeMap;
  }
}

export namespace UploadTemplateDataDocument {
  export enum StorageEnum {
    Cache = "cache",
  }
}
